[package]
name = "routing-wasm"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
config-model = { path = "../config-model" }
routing-core = { path = "../routing-core" }
pac-compiler = { path = "../pac-compiler" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
wasm-bindgen.workspace = true
